#@ load("github.lib.yml", "checkout", "cache_node", "setup_node")
#@ load("rush.lib.yml", "rush_add_path", "rush_install", "rush_build")
#@ load("sftp.lib.yml", "sftp_bunny_copy")
name: Deploy menu root

"on":
  push:
    branches:
      - 'feature/CI'
      - '*'
    #! paths:
    #!   -  #@ '**/*.json'
    #!   -  #@ '.github/**/*'

jobs:
  deploy-production:
    name: Deploy to Cloudflare menus-beta & Bunny menus
    runs-on: ubuntu-latest
    steps:
      -  #@ checkout()
      - name: Setup private SSH key to clone code repo
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
          git clone git@github.com:whatisedible/Edible
      -  #@ setup_node()
      -  #@ cache_node()
      -  #@ rush_add_path()
      -  #@ rush_install()
      -  #@ rush_build()
      - name: Build menu app
        run: cd apps/menu && rushx build:prod
        env:
          BASE_PATH: ""
          VITE_ACKEE_ID: aaabec74-24f9-4aca-89ad-f0fd54e2944f
        working-directory: ./Edible
      -  #@ sftp_bunny_copy(name="built app", src="apps/menu/build/*", dst="/")
      - name: Output link to deployed menu
        run: echo You can view the menu on https://menus.whatisedible.com/ | tee -a $GITHUB_STEP_SUMMARY
        working-directory: ./Edible
