#@ def rush_add_path():
name: Add local rush scripts to PATH
run: echo "${PWD}"/common/scripts >> $GITHUB_PATH
working-directory: ./Edible
#@ end
---
#@ def rush_install():
name: Install packages
run: rush update
working-directory: ./Edible
#@ end
---
#@ def rush_build():
name: Build packages
run: rush build
working-directory: ./Edible
#@ end
